title: SNAP Nutrient Solution for Hydroponics
email: snaphydroponics@gmail.com
description: >
  SNAP Nutrient Solution for Hydroponics. SNAP stands for Simple Nutrient
  Addition Program. It is a low-cost, low-maintenance hydroponics system that is
  designed for household and small-scale vegetable production.
url: https://manual.snaphydroponics.info
twitter_username: snaphydroponics
facebook_username: simple.nutrient.addition.program
instagram_username: snaphydroponics

# Build settings
author: Marco Enrico Alviar

plugins:
  #- jekyll-feed
  #- jekyll-seo-tag

markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
google_analytics: UA-29098575-5

collections:
  about:
    output: true
    permalink: /about/:path:output_ext
